### PR TITLE
Support for nested structs added.

### PR DESCRIPTION
**Pull request by rashuky**
Small upgrade that makes this work with nested structs as well.

### CODE REVIEW

**Comment by Dugy** [comment]
This actually breaks the intended use case. I was assuming it would be called in the style of:

```C++
template <typename T>
struct Serialiser<T, std::enable_if_t<std::is_aggregate_v<T>>* = nullptr> {
  static serialise(T& serialised) {
    foreachStructMember(serialised, [&serialiser] (auto& member) { serialiser.serialise(member); });
  }
};
```

And the `Serialiser` struct would be specialised to usual data types using some read/write functionality for those types and this specialisation for struct types. This way, it would work for nested structs too, but also with the extra that you have means of knowing you are in a nested type and the possibility of specialising it for types that are aggregates. With your addition, there is no way of doing that.

**Comment by Dugy** [comment]
If you have a different use case where the implicit traversal of nested structs matters, you can make this change require a flag template argument or something like that.

**Comment by rashuky** [comment]
I see. I will cancel my PR then.

Anyway, great work @Dugy ! I came across your work while I was trying to figure out a way to scan classes to find all getters (i.e., public methods that start with get), call them all, bind the results into a tuple, and then use those to compare two objects of the same type. I am dealing with the development of encoders/decoders using nanopb. I have a ton of non-trivially constructible classes with private attributes and a lot of nested classes within nested classes. All of them have getters. Basically, I need to check if object == Decode(encode(object)). Detecting all of the getters proved to be hard to do; I think it might be impossible without true support for reflection in C++.

I ended up providing a definition for every struct that manually calls those getters to create a tuple. It is a lot of boilerplate code, but still less than overriding every single operator==.

**Comment by Dugy** [comment]
I am intrigued. How can you actually use `foreachStructMember()` to construct a tuple from a POD struct? The only way I can think of is serialising both and comparing the result, or using `foreachStructMember()` on one and using another `foreachStructMember()` on the other one inside, comparing members on the same index and hoping the compiler can optimise the wrong matches out.

**Comment by rashuky** [comment]
I am not. I was using something else for that, but then I encountered your post on Reddit and thought it might be useful for me. It took me some time to understand it, as I am not very fluent with metaprogramming. In the end, unfortunately, it turned out it won't help in my case.

**Comment by Dugy** [comment]
It wasn't me who posted this on reddit, but that doesn't matter. I am surprised you understood it despite not seeing yourself as very fluent with metaprogramming, most of the audience saw it as _so I do this and this and then magic and I get member information._

I think you can use C++20 to declare `bool operator==(/* same type */) = default;` to get the code for comparing individual members generated. Alternatively, I think this should work too, but I am not sure how well will it optimise:

```C++
bool equals = true;
foreachStructMember(object1, [&equals, index1 = 0] (auto& element1) {
  foreachStructMember(object2, [&equals, index2 = 0] (auto& element2) {
    if constexpr(is_same<decltype(element1), decltype(element2)>) {
      if (index1 == index2) {
        if (element1 != element2) {
          equals = false;
          break;
        }
      }
    }
    index2++;
  });
  index1++;
});
```
(you may need your patch to compare the subobjects, but it can be handled with recursively calling this function on aggregates without an equality operator)

**Pull request closed without merging**
